

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."role" AS ENUM (
    'admin',
    'staff_admin',
    'staff',
    'student',
    'parent'
);


ALTER TYPE "public"."role" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admins" (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "auth_user_id" "uuid" NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "email" "text" NOT NULL,
    "status" "text" DEFAULT 'active'::"text",
    CONSTRAINT "admins_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);


ALTER TABLE "public"."admins" OWNER TO "postgres";


ALTER TABLE "public"."admins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."admins_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auditlogs" (
    "id" bigint NOT NULL,
    "action" "text" NOT NULL,
    "entity_type" "text" NOT NULL,
    "entity_id" bigint NOT NULL,
    "old_value" "jsonb",
    "new_value" "jsonb",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "actor_id" bigint NOT NULL,
    "actor_role" "public"."role" NOT NULL
);


ALTER TABLE "public"."auditlogs" OWNER TO "postgres";


ALTER TABLE "public"."auditlogs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auditlogs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."classes" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "year_group_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."classes" OWNER TO "postgres";


ALTER TABLE "public"."classes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."classes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."moderations" (
    "id" bigint NOT NULL,
    "student_id" bigint,
    "entity_type" "text" NOT NULL,
    "old_content" json,
    "new_content" json,
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "moderated_at" timestamp without time zone,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "old_attachment" "text",
    "new_attachment" "text",
    "action_type" "text" DEFAULT 'create'::"text",
    "rejection_reason" "text",
    "entity_id" bigint,
    "year_group_id" bigint,
    "class_id" bigint,
    "entity_title" "text" DEFAULT 'The Party :)'::"text" NOT NULL,
    CONSTRAINT "moderations_action_type_check" CHECK (("action_type" = ANY (ARRAY['create'::"text", 'update'::"text", 'delete'::"text"]))),
    CONSTRAINT "moderations_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."moderations" OWNER TO "postgres";


ALTER TABLE "public"."moderations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."moderations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pagetypes" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."pagetypes" OWNER TO "postgres";


ALTER TABLE "public"."pagetypes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pagetypes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."parents" (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "auth_user_id" "uuid",
    "first_name" "text",
    "last_name" "text",
    "email" "text",
    "password" "text",
    "status" "text" DEFAULT 'active'::"text",
    CONSTRAINT "parents_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);


ALTER TABLE "public"."parents" OWNER TO "postgres";


ALTER TABLE "public"."parents" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."parents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."parentstudentrelationship" (
    "id" bigint NOT NULL,
    "parent_id" bigint,
    "student_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."parentstudentrelationship" OWNER TO "postgres";


ALTER TABLE "public"."parentstudentrelationship" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."parentstudentrelationship_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."personalsections" (
    "id" bigint NOT NULL,
    "student_id" bigint,
    "topic_id" bigint,
    "content" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."personalsections" OWNER TO "postgres";


ALTER TABLE "public"."personalsections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."personalsections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."personalsectiontopics" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."personalsectiontopics" OWNER TO "postgres";


ALTER TABLE "public"."personalsectiontopics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."personalsectiontopics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."reflectioncomments" (
    "id" bigint NOT NULL,
    "reflection_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "comment" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "user_role" "text" NOT NULL,
    "user_name" "text" DEFAULT 'Tom'::"text" NOT NULL
);


ALTER TABLE "public"."reflectioncomments" OWNER TO "postgres";


ALTER TABLE "public"."reflectioncomments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reflectioncomments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."reflections" (
    "id" bigint NOT NULL,
    "student_id" bigint,
    "year_group_id" bigint,
    "topic_id" bigint,
    "content" "text",
    "attachment_url" "text",
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "week" "text" DEFAULT 'Week 1'::"text" NOT NULL
);


ALTER TABLE "public"."reflections" OWNER TO "postgres";


ALTER TABLE "public"."reflections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reflections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."reflectiontopics" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "created_by" bigint,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."reflectiontopics" OWNER TO "postgres";


ALTER TABLE "public"."reflectiontopics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reflectiontopics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."staff_admins" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "auth_user_id" "uuid" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text",
    "email" "text" NOT NULL,
    "password" "text",
    "status" "text" DEFAULT 'active'::"text",
    CONSTRAINT "staff_admins_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);


ALTER TABLE "public"."staff_admins" OWNER TO "postgres";


ALTER TABLE "public"."staff_admins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."staff_admins_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."staffs" (
    "id" bigint NOT NULL,
    "year_group_id" bigint,
    "class_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "auth_user_id" "uuid" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text",
    "email" "text" NOT NULL,
    "password" "text",
    "status" "text" DEFAULT 'active'::"text",
    CONSTRAINT "staffs_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);


ALTER TABLE "public"."staffs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."studentimages" (
    "id" bigint NOT NULL,
    "student_id" bigint,
    "year_group_id" bigint,
    "image_url" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "status" "text" DEFAULT 'accepted'::"text" NOT NULL
);


ALTER TABLE "public"."studentimages" OWNER TO "postgres";


ALTER TABLE "public"."studentimages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studentimages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."studentlearningentities" (
    "id" bigint NOT NULL,
    "student_id" bigint,
    "subject_id" bigint,
    "title" "text",
    "description" "text",
    "attachment_url" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."studentlearningentities" OWNER TO "postgres";


ALTER TABLE "public"."studentlearningentities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studentlearningentities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."studentpages" (
    "id" bigint NOT NULL,
    "student_id" bigint,
    "year_group_id" bigint,
    "page_type_id" bigint,
    "content" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."studentpages" OWNER TO "postgres";


ALTER TABLE "public"."studentpages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studentpages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."students" (
    "id" bigint NOT NULL,
    "year_group_id" bigint,
    "class_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "dob" timestamp without time zone,
    "profile_photo" "text",
    "hair_color" "text",
    "height" integer,
    "auth_user_id" "uuid" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text",
    "username" "text" NOT NULL,
    "email" "text" NOT NULL,
    "status" "text" DEFAULT 'active'::"text",
    "current_year_group_id" bigint DEFAULT '1'::bigint NOT NULL,
    CONSTRAINT "students_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);


ALTER TABLE "public"."students" OWNER TO "postgres";


ALTER TABLE "public"."students" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."students_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."subjects" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "status" "text" DEFAULT 'active'::"text" NOT NULL
);


ALTER TABLE "public"."subjects" OWNER TO "postgres";


ALTER TABLE "public"."subjects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subjects_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."staffs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."teachers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."year_group_subject" (
    "id" bigint NOT NULL,
    "year_group_id" bigint NOT NULL,
    "subject_id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."year_group_subject" OWNER TO "postgres";


ALTER TABLE "public"."year_group_subject" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."year_group_subject_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."yeargroups" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."yeargroups" OWNER TO "postgres";


ALTER TABLE "public"."yeargroups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."yeargroups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."admins"
    ADD CONSTRAINT "admins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auditlogs"
    ADD CONSTRAINT "auditlogs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."classes"
    ADD CONSTRAINT "classes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."moderations"
    ADD CONSTRAINT "moderations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pagetypes"
    ADD CONSTRAINT "pagetypes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."parents"
    ADD CONSTRAINT "parents_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."parents"
    ADD CONSTRAINT "parents_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."parents"
    ADD CONSTRAINT "parents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."parentstudentrelationship"
    ADD CONSTRAINT "parentstudentrelationship_parent_id_student_id_key" UNIQUE ("parent_id", "student_id");



ALTER TABLE ONLY "public"."parentstudentrelationship"
    ADD CONSTRAINT "parentstudentrelationship_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."personalsections"
    ADD CONSTRAINT "personalsections_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."personalsectiontopics"
    ADD CONSTRAINT "personalsectiontopics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reflectioncomments"
    ADD CONSTRAINT "reflectioncomments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reflections"
    ADD CONSTRAINT "reflections_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reflectiontopics"
    ADD CONSTRAINT "reflectiontopics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."staff_admins"
    ADD CONSTRAINT "staff_admins_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."staff_admins"
    ADD CONSTRAINT "staff_admins_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."staff_admins"
    ADD CONSTRAINT "staff_admins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studentimages"
    ADD CONSTRAINT "studentimages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studentlearningentities"
    ADD CONSTRAINT "studentlearningentities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studentpages"
    ADD CONSTRAINT "studentpages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subjects_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subjects_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."staffs"
    ADD CONSTRAINT "teachers_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."staffs"
    ADD CONSTRAINT "teachers_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."staffs"
    ADD CONSTRAINT "teachers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."year_group_subject"
    ADD CONSTRAINT "year_group_subject_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."year_group_subject"
    ADD CONSTRAINT "year_group_subject_year_group_id_subject_id_key" UNIQUE ("year_group_id", "subject_id");



ALTER TABLE ONLY "public"."yeargroups"
    ADD CONSTRAINT "yeargroups_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."yeargroups"
    ADD CONSTRAINT "yeargroups_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_admins_auth_user_id" ON "public"."admins" USING "btree" ("auth_user_id");



CREATE INDEX "idx_admins_email" ON "public"."admins" USING "btree" ("email");



CREATE INDEX "idx_moderations_status" ON "public"."moderations" USING "btree" ("status");



CREATE INDEX "idx_moderations_student" ON "public"."moderations" USING "btree" ("student_id");



CREATE INDEX "idx_moderations_year_class" ON "public"."moderations" USING "btree" ("year_group_id", "class_id");



CREATE INDEX "idx_parents_auth_user_id" ON "public"."parents" USING "btree" ("auth_user_id");



CREATE INDEX "idx_parents_email" ON "public"."parents" USING "btree" ("email");



CREATE INDEX "idx_parentstudentrelationship_parent" ON "public"."parentstudentrelationship" USING "btree" ("parent_id");



CREATE INDEX "idx_parentstudentrelationship_student" ON "public"."parentstudentrelationship" USING "btree" ("student_id");



CREATE INDEX "idx_reflectioncomments_reflection" ON "public"."reflectioncomments" USING "btree" ("reflection_id");



CREATE INDEX "idx_reflections_student" ON "public"."reflections" USING "btree" ("student_id");



CREATE INDEX "idx_reflections_student_topic" ON "public"."reflections" USING "btree" ("student_id", "topic_id");



CREATE INDEX "idx_reflections_student_week" ON "public"."reflections" USING "btree" ("student_id", "week");



CREATE INDEX "idx_reflectiontopics_active" ON "public"."reflectiontopics" USING "btree" ("is_active");



CREATE INDEX "idx_staff_admins_auth_user_id" ON "public"."staff_admins" USING "btree" ("auth_user_id");



CREATE INDEX "idx_staff_admins_email" ON "public"."staff_admins" USING "btree" ("email");



CREATE INDEX "idx_staffs_auth_user_id" ON "public"."staffs" USING "btree" ("auth_user_id");



CREATE INDEX "idx_staffs_email" ON "public"."staffs" USING "btree" ("email");



CREATE INDEX "idx_staffs_year_group_class" ON "public"."staffs" USING "btree" ("year_group_id", "class_id");



CREATE INDEX "idx_studentimages_student" ON "public"."studentimages" USING "btree" ("student_id");



CREATE INDEX "idx_studentimages_student_year" ON "public"."studentimages" USING "btree" ("student_id", "year_group_id");



CREATE INDEX "idx_studentlearningentities_student_subject" ON "public"."studentlearningentities" USING "btree" ("student_id", "subject_id");



CREATE INDEX "idx_studentpages_student_year_page" ON "public"."studentpages" USING "btree" ("student_id", "year_group_id", "page_type_id");



CREATE INDEX "idx_students_auth_user_id" ON "public"."students" USING "btree" ("auth_user_id");



CREATE INDEX "idx_students_email" ON "public"."students" USING "btree" ("email");



CREATE INDEX "idx_students_status" ON "public"."students" USING "btree" ("status");



CREATE INDEX "idx_students_year_group_class" ON "public"."students" USING "btree" ("year_group_id", "class_id");



CREATE INDEX "idx_subjects_status" ON "public"."subjects" USING "btree" ("status");



CREATE INDEX "idx_year_group_subject_year" ON "public"."year_group_subject" USING "btree" ("year_group_id");



ALTER TABLE ONLY "public"."moderations"
    ADD CONSTRAINT "moderations_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "public"."classes"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."moderations"
    ADD CONSTRAINT "moderations_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."moderations"
    ADD CONSTRAINT "moderations_year_group_id_fkey" FOREIGN KEY ("year_group_id") REFERENCES "public"."yeargroups"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."parentstudentrelationship"
    ADD CONSTRAINT "parentstudentrelationship_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."parents"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."parentstudentrelationship"
    ADD CONSTRAINT "parentstudentrelationship_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."personalsections"
    ADD CONSTRAINT "personalsections_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."personalsections"
    ADD CONSTRAINT "personalsections_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "public"."personalsectiontopics"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reflectioncomments"
    ADD CONSTRAINT "reflectioncomments_reflection_id_fkey" FOREIGN KEY ("reflection_id") REFERENCES "public"."reflections"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reflections"
    ADD CONSTRAINT "reflections_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reflections"
    ADD CONSTRAINT "reflections_topic_id_fkey" FOREIGN KEY ("topic_id") REFERENCES "public"."reflectiontopics"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reflectiontopics"
    ADD CONSTRAINT "reflectiontopics_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."staffs"("id");



ALTER TABLE ONLY "public"."staffs"
    ADD CONSTRAINT "staffs_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "public"."classes"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."staffs"
    ADD CONSTRAINT "staffs_year_group_id_fkey" FOREIGN KEY ("year_group_id") REFERENCES "public"."yeargroups"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."studentimages"
    ADD CONSTRAINT "studentimages_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studentimages"
    ADD CONSTRAINT "studentimages_year_group_id_fkey" FOREIGN KEY ("year_group_id") REFERENCES "public"."yeargroups"("id");



ALTER TABLE ONLY "public"."studentlearningentities"
    ADD CONSTRAINT "studentlearningentities_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studentlearningentities"
    ADD CONSTRAINT "studentlearningentities_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studentpages"
    ADD CONSTRAINT "studentpages_page_type_id_fkey" FOREIGN KEY ("page_type_id") REFERENCES "public"."pagetypes"("id");



ALTER TABLE ONLY "public"."studentpages"
    ADD CONSTRAINT "studentpages_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studentpages"
    ADD CONSTRAINT "studentpages_year_group_id_fkey" FOREIGN KEY ("year_group_id") REFERENCES "public"."yeargroups"("id");



ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "public"."classes"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_current_year_group_id_fkey" FOREIGN KEY ("current_year_group_id") REFERENCES "public"."yeargroups"("id");



ALTER TABLE ONLY "public"."year_group_subject"
    ADD CONSTRAINT "year_group_subject_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."year_group_subject"
    ADD CONSTRAINT "year_group_subject_year_group_id_fkey" FOREIGN KEY ("year_group_id") REFERENCES "public"."yeargroups"("id") ON DELETE CASCADE;



CREATE POLICY "Enable read access for authenticated users" ON "public"."yeargroups" FOR SELECT TO "authenticated" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."admins" TO "anon";
GRANT ALL ON TABLE "public"."admins" TO "authenticated";
GRANT ALL ON TABLE "public"."admins" TO "service_role";



GRANT ALL ON SEQUENCE "public"."admins_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."admins_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."admins_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auditlogs" TO "anon";
GRANT ALL ON TABLE "public"."auditlogs" TO "authenticated";
GRANT ALL ON TABLE "public"."auditlogs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auditlogs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auditlogs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auditlogs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."classes" TO "anon";
GRANT ALL ON TABLE "public"."classes" TO "authenticated";
GRANT ALL ON TABLE "public"."classes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."classes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."classes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."classes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."moderations" TO "anon";
GRANT ALL ON TABLE "public"."moderations" TO "authenticated";
GRANT ALL ON TABLE "public"."moderations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."moderations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."moderations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."moderations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pagetypes" TO "anon";
GRANT ALL ON TABLE "public"."pagetypes" TO "authenticated";
GRANT ALL ON TABLE "public"."pagetypes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pagetypes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pagetypes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pagetypes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."parents" TO "anon";
GRANT ALL ON TABLE "public"."parents" TO "authenticated";
GRANT ALL ON TABLE "public"."parents" TO "service_role";



GRANT ALL ON SEQUENCE "public"."parents_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."parents_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."parents_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."parentstudentrelationship" TO "anon";
GRANT ALL ON TABLE "public"."parentstudentrelationship" TO "authenticated";
GRANT ALL ON TABLE "public"."parentstudentrelationship" TO "service_role";



GRANT ALL ON SEQUENCE "public"."parentstudentrelationship_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."parentstudentrelationship_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."parentstudentrelationship_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."personalsections" TO "anon";
GRANT ALL ON TABLE "public"."personalsections" TO "authenticated";
GRANT ALL ON TABLE "public"."personalsections" TO "service_role";



GRANT ALL ON SEQUENCE "public"."personalsections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."personalsections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."personalsections_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."personalsectiontopics" TO "anon";
GRANT ALL ON TABLE "public"."personalsectiontopics" TO "authenticated";
GRANT ALL ON TABLE "public"."personalsectiontopics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."personalsectiontopics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."personalsectiontopics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."personalsectiontopics_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."reflectioncomments" TO "anon";
GRANT ALL ON TABLE "public"."reflectioncomments" TO "authenticated";
GRANT ALL ON TABLE "public"."reflectioncomments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reflectioncomments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reflectioncomments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reflectioncomments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."reflections" TO "anon";
GRANT ALL ON TABLE "public"."reflections" TO "authenticated";
GRANT ALL ON TABLE "public"."reflections" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reflections_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reflections_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reflections_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."reflectiontopics" TO "anon";
GRANT ALL ON TABLE "public"."reflectiontopics" TO "authenticated";
GRANT ALL ON TABLE "public"."reflectiontopics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reflectiontopics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reflectiontopics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reflectiontopics_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."staff_admins" TO "anon";
GRANT ALL ON TABLE "public"."staff_admins" TO "authenticated";
GRANT ALL ON TABLE "public"."staff_admins" TO "service_role";



GRANT ALL ON SEQUENCE "public"."staff_admins_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."staff_admins_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."staff_admins_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."staffs" TO "anon";
GRANT ALL ON TABLE "public"."staffs" TO "authenticated";
GRANT ALL ON TABLE "public"."staffs" TO "service_role";



GRANT ALL ON TABLE "public"."studentimages" TO "anon";
GRANT ALL ON TABLE "public"."studentimages" TO "authenticated";
GRANT ALL ON TABLE "public"."studentimages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studentimages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studentimages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studentimages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."studentlearningentities" TO "anon";
GRANT ALL ON TABLE "public"."studentlearningentities" TO "authenticated";
GRANT ALL ON TABLE "public"."studentlearningentities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studentlearningentities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studentlearningentities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studentlearningentities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."studentpages" TO "anon";
GRANT ALL ON TABLE "public"."studentpages" TO "authenticated";
GRANT ALL ON TABLE "public"."studentpages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studentpages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studentpages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studentpages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."students" TO "anon";
GRANT ALL ON TABLE "public"."students" TO "authenticated";
GRANT ALL ON TABLE "public"."students" TO "service_role";



GRANT ALL ON SEQUENCE "public"."students_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."students_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."students_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."subjects" TO "anon";
GRANT ALL ON TABLE "public"."subjects" TO "authenticated";
GRANT ALL ON TABLE "public"."subjects" TO "service_role";



GRANT ALL ON SEQUENCE "public"."subjects_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."subjects_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subjects_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."teachers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."teachers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."teachers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."year_group_subject" TO "anon";
GRANT ALL ON TABLE "public"."year_group_subject" TO "authenticated";
GRANT ALL ON TABLE "public"."year_group_subject" TO "service_role";



GRANT ALL ON SEQUENCE "public"."year_group_subject_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."year_group_subject_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."year_group_subject_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."yeargroups" TO "anon";
GRANT ALL ON TABLE "public"."yeargroups" TO "authenticated";
GRANT ALL ON TABLE "public"."yeargroups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."yeargroups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."yeargroups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."yeargroups_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;

  create policy "Enable insert for authenticated users only"
  on "storage"."buckets"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Allow authenticated users to upload images gxiyis_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'barrowford-school-uploads'::text));



  create policy "Give users access to own folder gxiyis_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'barrowford-school-uploads'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder gxiyis_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'barrowford-school-uploads'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder gxiyis_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'barrowford-school-uploads'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder gxiyis_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'barrowford-school-uploads'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users authenticated access to folder gxiyis_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'barrowford-school-uploads'::text) AND ((storage.foldername(name))[1] = 'private'::text) AND (auth.role() = 'authenticated'::text)));



