create table public.student_experiences (
  id bigint generated by default as identity not null,
  student_id bigint null,
  year_group_id bigint null,
  title text null,
  description text null,
  attachment_url text null,
  created_at timestamp without time zone null default now(),
  status text not null default 'approved'::text,
  constraint studentexperiences_pkey primary key (id),
  constraint studentexperiences_student_id_fkey foreign KEY (student_id) references students (id) on delete CASCADE,
  constraint studentexperiences_year_group_id_fkey foreign KEY (year_group_id) references year_groups (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_studentexperiences_student on public.student_experiences using btree (student_id) TABLESPACE pg_default;
create index IF not exists idx_studentexperiences_student_year on public.student_experiences using btree (student_id, year_group_id) TABLESPACE pg_default;

